version: '{build}'
skip_non_tags: false
image: Visual Studio 2017
clone_folder: c:\projects\dss_python
cache:
  - c:\projects\VCForPython27.msi
  - c:\projects\FPC-win32-win64-3.0.4.7z
  - c:\projects\SuiteSparse-5.3.0.tar.gz
environment:
  ANACONDA_API_TOKEN: 
    secure: 78d9aslKXYoP2gVc7p5A5BJj3bSDPd2kZjQAlvEd64cCcxaf185CexeDNYNeNPuU
  matrix:
    - CONDA_SUBDIR: win-32
    - CONDA_SUBDIR: win-64
    
build_script:
- cmd: call ci\build_appveyor.bat
    
test: off