package:
    name: dss_python
    version: "{{ load_setup_py_data().version }}"
    
source:
    #git_rev: "0.10.2"
    #git_url: https://github.com/dss-extensions/dss_python.git
    path: ..
    
build:
    script_env:
        - DSS_CAPI_PATH

requirements:
    build:
        - {{ compiler('c') }}
#        - {{ compiler('cxx') }}
        - python {{ python }}
        - cffi
        - setuptools
        - wheel
        - cmake [osx]
        # - git
        
    host:
        - python
        - setuptools
        - cffi
        
    run: 
        - python
        - cffi
        - numpy

