package:
    name: dss_python
    version: "0.10.1"
    
source:
    git_rev: "0.10.1"
    git_url: https://github.com/dss-extensions/dss_python.git
    #path: ..
    
build:
    script_env:
        - SUITESPARSE_SRC

requirements:
    build:
        - {{ compiler('c') }} # [linux]
        - {{ compiler('cxx') }} # [linux]
        - python {{ python }}
        - cffi
        - setuptools
        - wheel
        - cmake [osx]
        # - {{ compiler('pascal') }}
        # - git
        
    host:
        - python
        - setuptools
        - cffi
        
    run: 
        - python
        - cffi
        - numpy

